defaults: &defaults
  latest_commit: 4ff6ff5608f2590dd7cd4df809382c50c51c117f
  api_url: https://beta2.osidori-dev.com
  at_url: https://atdev.369webcash.com
  at_pwd_salt: osdrdev
  at_chnl_id: CHNL_OSIDORI
  at_account_name_prefix: osdrdev
  at_sync_transaction_max_days: 90
  at_user_limit_free_account: 5
  at_user_limit_free_goal: 5
  mail_setting_from: OsidOri <info@osidori.co>
  mail_content_type: multipart/alternative
  mail_charset: ISO-2022-JP
  pairing_token_salt: 2dhp2fw5gra4aks
  s3_img_url: https://osdr-img-test.s3-ap-northeast-1.amazonaws.com

test:
  <<: *defaults
  api_url: https://beta2.osidori-dev.com
  at_url: https://atdev.369webcash.com
  at_pwd_salt: osdrdev
  at_chnl_id: CHNL_OSIDORI
  at_account_name_prefix: osdrdev

development:
  <<: *defaults
  api_url: https://beta2.osidori-dev.com
  at_url: https://atdev.369webcash.com
  at_pwd_salt: osdrdev
  at_chnl_id: CHNL_OSIDORI
  at_account_name_prefix: osdrdev

staging:
  <<: *defaults
  api_url: https://stg-api.osidori-dev.com
  at_url: https://atstaging.369webcash.com
  at_pwd_salt: osdrstaging
  at_chnl_id: CHNL_OSIDORI
  at_account_name_prefix: osdrstaging
  s3_img_url: https://osidori-img-stg.s3-ap-northeast-1.amazonaws.com

production:
  <<: *defaults
  api_url: https://api-osidori.com
  at_url: https://at.369webcash.com
  at_pwd_salt: osdr
  at_chnl_id: CHNL_OSIDORI
  at_account_name_prefix: osdr
  s3_img_url: https://osidori-img.s3-ap-northeast-1.amazonaws.com